# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tuomas Salmi
author: Tuomas Salmi
description: >
  Passion for learning, science and software
meta_title: Tuomas Salmi Homepage
meta_description: Tuomas Salmi, home page. Art, games and software.

cover: "covers/cliffs.jpg"
portrait: "portrait.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tumetsu.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social details. Both for SEO and elements in layout
twitter:
  username: tumetsu
github_username:  tumetsu
linkedin_url: https://fi.linkedin.com/in/salmituomas
social:
  name: Tuomas Salmi
  links:
  - https://fi.linkedin.com/in/salmituomas
  - https://twitter.com/tumetsu
  - https://github.com/Tumetsu

# Details for services used in page
disqus: tuomassalmi
google_analytics: UA-76209187-1
rss: https://feedburner.google.com/fb/a/mailverify?uri=TuomasSalmi

# Build settings
images: '/assets/images'
navigation: true
collections:
  navigation_pages:
    output: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima
paginate: 8
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - bower.json
  - .gitignore
  - src
  - bleak
  - bower_components
  - node_modules
  - themes']
