# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tuomas Salmi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Passion for learning, science and software
cover: "cliffs.jpg"
portrait: "portrait.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tumetsu
github_username:  tumetsu
linkedin_url: https://fi.linkedin.com/in/salmituomas
disqus: tuomassalmi
#google_analytics: UA-76209187-1
rss: https://feedburner.google.com/fb/a/mailverify?uri=TuomasSalmi
meta_title: stuff
meta_description: stuffity stuff
images: '/assets/images'
navigation: true
collections:
  navigation_pages:
    output: true

# Build settings
markdown: kramdown
theme: minima
paginate: 8
#paginate_path: "/blog/page:num/"
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - bower.json
  - .gitignore
  - src
  - bleak
  - bower_components
  - node_modules
  - themes']
